services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - app_network

###########################################################################################
  chroma:
    image: chromadb/chroma
    container_name: chromadb
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - chroma_data:/chroma/chroma
    networks:
      - app_network

  redis:
    image: redis:alpine
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
    networks:
      - app_network

volumes:
  redis_data:
  ollama_data:
  chroma_data:


networks:
  app_network:
    driver: bridge